### PR TITLE
Close #8 Add Bidirectional stream with GRPC

### LINKED ISSUE #8: RESAURCE_EXHAUSTED - max message size
Can't make max messages size larger than 209715200. Channel configuration is ok, but server can't take it.

error:

_grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "grpc: received message larger than max (236075865 vs. 209715200)"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:3333 {grpc_message:"grpc: received message larger than max (236075865 vs. 209715200)", grpc_status:8, created_time:"2024-07-29T11:06:44.1927981+00:00"}"_

code:

MAX_MESSAGE_LENGTH = (2 ** 20) * 500
class A2lParser(object):
    def __init__(self, string):
        self._dll = ctypes.cdll.LoadLibrary(os.path.join(os.path.dirname(__file__), 'a2l_grpc', get_shared_object_name()))
        channel = grpc.insecure_channel('localhost:3333', options=[
        ('grpc.max_message_length', MAX_MESSAGE_LENGTH),
        ('grpc.max_send_message_length', MAX_MESSAGE_LENGTH),
        ('grpc.max_receive_message_length', MAX_MESSAGE_LENGTH),
    ])
        client = A2LStub(channel)
        if self._dll.Create(3333):
            raise Exception(1)
        self.ast = client.GetTreeFromA2L(TreeFromA2LRequest(a2l=string.encode())).tree

### PR DESCRIPTION
**Pull request by iromzy**
The bidirectional stream has been added for use with GRPC, and the tests have been adapted with stream mocking to run the tests.

I've set the default size per chunk to 4MB, this is the default value for the Grpc stream, it can be modified, it's a constant.

The golang version has been updated to version 1.22.11 and protoc to version 29.3.

Of course, we now need to adapt the client side, i.e. PyA2L.

### CODE REVIEW

**Comment by iromzy** [comment]
It is main or develop branch for the pull request ?

File: cmd/a2l/a2l.go [hunk 1]
```diff
@@ -68,114 +83,232 @@ func getTreeFromString(a2lString string) (result *a2l.RootNodeType, err error) {
...
 	}
-
-	if request.Sorted != nil {
-		sorted = *request.Sorted
+	if err == nil {
+		if err = proto.Unmarshal(buffer.Bytes(), tree); err == nil {
+			a2lDataBytes = []byte(tree.MarshalA2L(0, indent, sorted))
+			for _, chunk = range chunkifyBySize(a2lDataBytes, s.chunkSize) {
+				response.A2L = chunk
+				err = stream.Send(response)
```
Comment (Sauci) [inline cmd/a2l/a2l.go:298]: The `err` value is silently ignored here, right?

File: cmd/a2l/a2l.go [hunk 2]
```diff
@@ -68,114 +83,232 @@ func getTreeFromString(a2lString string) (result *a2l.RootNodeType, err error) {
...
-		result.Error = &errString
+	if err == nil {
+		if tree, parseError = getTreeFromString(buffer.String()); parseError == nil {
+			if serializedTree, err = proto.Marshal(tree); err == nil {
+				for _, chunk = range chunkifyBySize(serializedTree, s.chunkSize) {
+					response.SerializedTreeChunk = chunk
+					err = stream.Send(response)
+				}
+			} else {
+				response.Error = proto.String(fmt.Sprintf("An error occure during serialization of Tree: %v", err))
```
Comment (Sauci) [inline cmd/a2l/a2l.go:118]: *occure* should be *occured*

File: cmd/a2l/a2l.go [hunk 3]
```diff
@@ -68,114 +83,232 @@ func getTreeFromString(a2lString string) (result *a2l.RootNodeType, err error) {
...
+				EmitUnpopulated: emitUnpopulated}
+
+			if rawData, parseError = opt.Marshal(tree); parseError == nil {
+				// Note: see https://github.com/golang/protobuf/issues/1121
+				var indentedBuffer bytes.Buffer
+				if err = json.Indent(&indentedBuffer, rawData, "", indent); err == nil {
+					rawData = indentedBuffer.Bytes()
+					for _, chunk = range chunkifyBySize(rawData, s.chunkSize) {
+						response.Json = chunk
+						err = stream.Send(response)
```
Comment (Sauci) [inline cmd/a2l/a2l.go:184]: If the `stream.Send` function fails, the error is silently ignored here.

**Review by Sauci — CHANGES_REQUESTED** [review]

File: cmd/a2l/a2l.go (hunk 1 above)
Comment (iromzy) [reply cmd/a2l/a2l.go:298]: Because we return directly this err variable
